development:
  adapter: postgresql
  encoding: unicode
  database: website_development
  pool: 5
  host: localhost
  username: ideesbebe
  password: sefsef

test:
  adapter: postgresql
  encoding: unicode
  database: website_test
  host: localhost
  pool: 5
  username: ideesbebe
  password: sefsef

production:
  adapter: postgresql
  encoding: unicode
  database: website_production
  host: localhost
  pool: 5
  username: ideesbebe
  password: sefsef
